const ADMIN_EMAIL = 'admin@mrinalscreations.com';
const ADMIN_PASSWORD = 'mrinal123';
let products = [];
const $ = id => document.getElementById(id);
async function getProducts() { const saved = localStorage.getItem('mrinalProducts'); if (saved) return JSON.parse(saved); const response = await fetch('products.json'); return response.json(); }
function persist() { localStorage.setItem('mrinalProducts', JSON.stringify(products)); }
function clearForm() { ['productId','productName','productPrice','productShort','productImage','productLong'].forEach(id => $(id).value = ''); $('imageFile').value = ''; }
function renderAdmin() { $('adminProducts').innerHTML = products.map(p => `<article class="admin-product"><img src="${p.image}" alt=""><div><strong>${p.name}</strong><span>₹${p.price}</span><small>${p.short}</small></div><button class="btn" data-edit="${p.id}">Edit</button><button class="btn" data-delete="${p.id}">Delete</button></article>`).join(''); }
$('loginForm').addEventListener('submit', async event => { event.preventDefault(); if ($('adminEmail').value !== ADMIN_EMAIL || $('adminPassword').value !== ADMIN_PASSWORD) return alert('Incorrect demo login details.'); products = await getProducts(); $('loginPanel').classList.add('hidden'); $('dashboard').classList.remove('hidden'); renderAdmin(); });
$('productForm').addEventListener('submit', event => { event.preventDefault(); const id = $('productId').value; const current = products.find(p => String(p.id) === id); const product = { id: id ? Number(id) : Math.max(0, ...products.map(p => Number(p.id))) + 1, name: $('productName').value, price: Number($('productPrice').value), short: $('productShort').value, long: $('productLong').value, image: $('productImage').value || current?.image || 'https://placehold.co/600x400?text=New+Creation', upi: current?.upi || '14bbt1019@okicici' }; products = id ? products.map(p => String(p.id) === id ? product : p) : [...products, product]; persist(); renderAdmin(); clearForm(); alert('Product saved.'); });
$('imageFile').addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => $('productImage').value = reader.result; reader.readAsDataURL(file); });
$('adminProducts').addEventListener('click', event => { const id = event.target.dataset.edit || event.target.dataset.delete; if (!id) return; const product = products.find(p => String(p.id) === id); if (event.target.dataset.edit) { $('productId').value = product.id; $('productName').value = product.name; $('productPrice').value = product.price; $('productShort').value = product.short; $('productImage').value = product.image; $('productLong').value = product.long; window.scrollTo({ top: 0, behavior: 'smooth' }); } else if (confirm(`Delete ${product.name}?`)) { products = products.filter(p => String(p.id) !== id); persist(); renderAdmin(); } });
$('cancelEdit').addEventListener('click', clearForm); $('logoutBtn').addEventListener('click', () => location.reload()); $('exportBtn').addEventListener('click', () => { const blob = new Blob([JSON.stringify(products, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'products.json'; link.click(); URL.revokeObjectURL(link.href); });