const DEFAULT_SETTINGS = { email: 'admin@mrinalscreations.com', password: 'mrinal123', name: "Mrinal's", brand: 'Creations', upi: '14bbt1019@okicici', contact: '14bbt1019@gmail.com', cod: true };
let products = [];
let settings = { ...DEFAULT_SETTINGS };
let apiMode = false;
const $ = id => document.getElementById(id);
async function getProducts() { const response = await fetch('/api/products'); if (!response.ok) throw new Error('API unavailable'); apiMode = true; return response.json(); }
async function getLocalProducts() { const saved = localStorage.getItem('mrinalProducts'); if (saved) return JSON.parse(saved); const response = await fetch('products.json'); return response.json(); }
function getSettings() { const saved = localStorage.getItem('mrinalSettings'); return saved ? { ...DEFAULT_SETTINGS, ...JSON.parse(saved) } : { ...DEFAULT_SETTINGS }; }
function fillSettings() { $('settingEmail').value = settings.email; $('settingName').value = settings.name; $('settingBrand').value = settings.brand; $('settingUpi').value = settings.upi; $('settingContact').value = settings.contact; $('settingCod').checked = settings.cod; }
function clearForm() { ['productId','productName','productPrice','productShort','productImage','productLong'].forEach(id => $(id).value = ''); $('imageFile').value = ''; }
function renderAdmin() { $('adminProducts').innerHTML = products.map(p => `<article class="admin-product"><img src="${p.image}" alt=""><div><strong>${p.name}</strong><span>₹${p.price}</span><small>${p.short}</small></div><button class="btn" data-edit="${p.id}">Edit</button><button class="btn" data-delete="${p.id}">Delete</button></article>`).join(''); }
$('loginForm').addEventListener('submit', async event => { event.preventDefault(); settings = getSettings(); const credentials = { email: $('adminEmail').value, password: $('adminPassword').value }; try { const response = await fetch('/api/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(credentials) }); if (!response.ok) throw new Error('Invalid login'); apiMode = true; products = await getProducts(); settings = await fetch('/api/settings').then(response => response.json()); } catch (error) { if (apiMode || (credentials.email !== settings.email || credentials.password !== settings.password)) return alert('Incorrect admin login details.'); products = await getLocalProducts(); } fillSettings(); $('loginPanel').classList.add('hidden'); $('dashboard').classList.remove('hidden'); renderAdmin(); });
$('settingsForm').addEventListener('submit', async event => { event.preventDefault(); settings = { ...settings, email: $('settingEmail').value.trim(), password: $('settingPassword').value.trim() || settings.password, name: $('settingName').value.trim(), brand: $('settingBrand').value.trim(), upi: $('settingUpi').value.trim(), contact: $('settingContact').value.trim(), cod: $('settingCod').checked }; if (apiMode) await fetch('/api/settings', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(settings) }); else localStorage.setItem('mrinalSettings', JSON.stringify(settings)); $('settingPassword').value = ''; alert('Store settings saved.'); });
$('productForm').addEventListener('submit', async event => { event.preventDefault(); const id = $('productId').value; if (apiMode) { const body = new FormData(); body.append('name', $('productName').value); body.append('price', $('productPrice').value); body.append('short', $('productShort').value); body.append('long', $('productLong').value); body.append('image', $('productImage').value); body.append('upi', settings.upi); if ($('imageFile').files[0]) body.append('imageFile', $('imageFile').files[0]); const response = await fetch(id ? `/api/products/${id}` : '/api/products', { method: id ? 'PUT' : 'POST', body }); if (!response.ok) return alert('Could not save product.'); products = await getProducts(); } else { const current = products.find(p => String(p.id) === id); const product = { id: id ? Number(id) : Math.max(0, ...products.map(p => Number(p.id))) + 1, name: $('productName').value, price: Number($('productPrice').value), short: $('productShort').value, long: $('productLong').value, image: $('productImage').value || current?.image || 'https://placehold.co/600x400?text=New+Creation', upi: settings.upi }; products = id ? products.map(p => String(p.id) === id ? product : p) : [...products, product]; localStorage.setItem('mrinalProducts', JSON.stringify(products)); } renderAdmin(); clearForm(); alert('Product saved permanently.'); });
$('imageFile').addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => $('productImage').value = reader.result; reader.readAsDataURL(file); });
$('adminProducts').addEventListener('click', async event => { const id = event.target.dataset.edit || event.target.dataset.delete; if (!id) return; const product = products.find(p => String(p.id) === id); if (event.target.dataset.edit) { $('productId').value = product.id; $('productName').value = product.name; $('productPrice').value = product.price; $('productShort').value = product.short; $('productImage').value = product.image; $('productLong').value = product.long; window.scrollTo({ top: 0, behavior: 'smooth' }); } else if (confirm(`Delete ${product.name}?`)) { if (apiMode) await fetch(`/api/products/${id}`, { method: 'DELETE' }); products = products.filter(p => String(p.id) !== id); if (!apiMode) localStorage.setItem('mrinalProducts', JSON.stringify(products)); renderAdmin(); } });
$('cancelEdit').addEventListener('click', clearForm); $('logoutBtn').addEventListener('click', () => location.reload()); $('exportBtn').addEventListener('click', () => { const blob = new Blob([JSON.stringify(products, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'products.json'; link.click(); URL.revokeObjectURL(link.href); });
