const defaultSettings = { name: "Mrinal's", brand: 'Creations', upi: '14bbt1019@okicici', contact: '14bbt1019@gmail.com', cod: true };
let apiMode = false;
async function loadProducts() { try { const response = await fetch('/api/products'); if (!response.ok) throw new Error('API unavailable'); apiMode = true; return response.json(); } catch (error) { const saved = localStorage.getItem('mrinalProducts'); if (saved) return JSON.parse(saved); return fetch('products.json').then(response => response.json()); } }
function loadSettings() { const saved = localStorage.getItem('mrinalSettings'); return saved ? { ...defaultSettings, ...JSON.parse(saved) } : defaultSettings; }
async function refreshSettings() { if (apiMode) { try { return await fetch('/api/settings').then(response => response.json()); } catch (error) {} } return loadSettings(); }
function applySettings(settings = loadSettings()) { document.querySelectorAll('[data-store-name]').forEach(node => node.textContent = settings.name); document.querySelectorAll('[data-store-brand]').forEach(node => node.textContent = settings.brand); document.querySelectorAll('[data-upi]').forEach(node => node.textContent = settings.upi); document.querySelectorAll('[data-cod]').forEach(node => node.textContent = settings.cod ? 'Cash on Delivery available' : 'Online payment available'); document.querySelectorAll('[data-contact]').forEach(node => node.textContent = settings.contact); document.querySelectorAll('[data-contact-link]').forEach(node => node.href = `mailto:${settings.contact}`); }
function el(tag, cls, html) { const element = document.createElement(tag); if (cls) element.className = cls; if (html !== undefined) element.innerHTML = html; return element; }
function formatPrice(price) { return `₹${price}`; }
function categoryFor(product) { const name = product.name.toLowerCase(); if (name.includes('t-shirt')) return 'shirt'; if (name.includes('handkerchief')) return 'handkerchief'; if (name.includes('custom')) return 'custom'; return 'hoop'; }
function imageFallback(event) { event.target.src = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 400"%3E%3Crect width="600" height="400" fill="%23f9d5e3"/%3E%3Ctext x="50%25" y="50%25" dominant-baseline="middle" text-anchor="middle" fill="%2354263d" font-family="Georgia" font-size="28"%3EMrinal%27s Creations%3C/text%3E%3C/svg%3E'; event.target.onerror = null; }
async function renderList() { const products = await loadProducts(); applySettings(await refreshSettings()); const container = document.getElementById('products'); const search = document.getElementById('searchProducts'); const category = document.getElementById('categoryProducts'); const draw = (term = '', selectedCategory = 'all') => { container.innerHTML = ''; const visibleProducts = products.filter(p => selectedCategory === 'all' || categoryFor(p) === selectedCategory).filter(p => `${p.name} ${p.short}`.toLowerCase().includes(term.toLowerCase())); visibleProducts.forEach(p => { const card = el('article', 'product-card'); card.innerHTML = `<img src="${p.image}" alt="${p.name}" loading="lazy" onerror="imageFallback(event)"><h3>${p.name}</h3><p class="price">${formatPrice(p.price)}</p><p class="desc">${p.short}</p><a class="btn" href="product.html?id=${p.id}">View / Order</a>`; container.appendChild(card); }); if (!visibleProducts.length) container.innerHTML = '<p class="empty-state">No creations match your search.</p>'; }; draw(); search?.addEventListener('input', event => draw(event.target.value, category.value)); category?.addEventListener('change', event => draw(search.value, event.target.value)); window.addEventListener('storage', event => { if (event.key === 'mrinalProducts' || event.key === 'mrinalSettings') window.location.reload(); }); }
function getQueryParam(name) { return new URLSearchParams(window.location.search).get(name); }
function copyToClipboard(text) { return navigator.clipboard ? navigator.clipboard.writeText(text) : Promise.resolve(); }
async function renderProduct() { const products = await loadProducts(); const p = products.find(product => String(product.id) === getQueryParam('id')); applySettings(await refreshSettings()); const container = document.getElementById('product'); if (!p) { container.innerHTML = '<p>Product not found.</p>'; return; } container.innerHTML = `<div class="product-main"><img src="${p.image}" alt="${p.name}" onerror="imageFallback(event)"><div class="product-info"><h2>${p.name}</h2><p class="price">${formatPrice(p.price)}</p><p>${p.long}</p><p><strong>Payment:</strong> UPI (<span data-upi>${p.upi}</span>) • <span data-cod>Cash on Delivery available</span></p><button id="orderBtn" class="btn primary">Order / Customise</button> <button id="copyLink" class="btn">Copy link</button></div></div><div id="orderFormWrap" class="order-form-wrap hidden"><h3>Order: ${p.name}</h3><form id="orderForm"><label>Name<br><input name="buyerName" required></label><label>Phone<br><input name="phone" required></label><label>Quantity<br><input name="qty" type="number" value="1" min="1" required></label><label>Address<br><textarea name="address"></textarea></label><label>Custom requirement / notes<br><textarea name="notes"></textarea></label><div class="form-actions"><button type="submit" class="btn primary">Send Order (open email)</button><button type="button" id="cancelOrder" class="btn">Cancel</button></div></form></div>`; applySettings(await refreshSettings()); document.getElementById('orderBtn').addEventListener('click', () => document.getElementById('orderFormWrap').classList.remove('hidden')); document.getElementById('copyLink').addEventListener('click', async () => { await copyToClipboard(window.location.href); alert('Product link copied to clipboard'); }); document.getElementById('cancelOrder').addEventListener('click', () => document.getElementById('orderFormWrap').classList.add('hidden')); document.getElementById('orderForm').addEventListener('submit', event => { event.preventDefault(); const data = new FormData(event.target); const current = loadSettings(); const body = `Hello,%0D%0A%0D%0AI'd like to order ${p.name}.%0D%0AName: ${data.get('buyerName')}%0D%0APhone: ${data.get('phone')}%0D%0AQuantity: ${data.get('qty')}%0D%0AAddress: ${data.get('address') || 'N/A'}%0D%0ANotes: ${data.get('notes') || 'N/A'}%0D%0APayment: UPI ${current.upi}${current.cod ? ' or Cash on Delivery' : ''}`; window.location.href = `mailto:${encodeURIComponent(current.contact)}?subject=${encodeURIComponent(`Order: ${p.name}`)}&body=${body}`; }); }
applySettings(); if (window.location.pathname.endsWith('product.html')) renderProduct(); else renderList();
